---
- name: Upgrade Stream container image and restart
  hosts: all
  become: yes

  tasks:

    - name: Pull image and recreate container if changed
      community.docker.docker_compose_v2:
        project_src: "{{ stream_dir }}"
        pull: always

# ansible-playbook upgrade_and_run_stream.yaml --limit serverX,serverY -e stream_version=VERSION_TAG_HERE
# leave -e stream_version empty to use the latest version from group_vars
