---
- name: Pull latest Stream image
  hosts: all
  become: yes
  vars:
    image_version: "{{ stream_version }}"

  tasks:
    - name: Pull the specified Stream image
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_version }}"
        source: pull
      register: pull_result

    - name: Show image pull result
      ansible.builtin.debug:
        msg:
          - "Image '{{ image_name }}:{{ image_version }}' pull changed: {{ pull_result.changed }}"
          - "Image ID: {{ pull_result.image.Id }}"

    - name: Show pulled image build date
      ansible.builtin.debug:
        msg: "Image '{{ image_name }}:{{ image_version }}' was built at: {{ pull_result.image.Created }}"

# pass a specific version if needed, latest is the default from group_vars.
# e.g: ansible-playbook -i inventory.ini upgrade_stream.yaml -e stream_version=beta -l=test_lab
