ansible_user: "your_ssh_user"
ansible_password: "your_ssh_password"  # pragma: allowlist secret
ansible_become_password: "your_sudo_password"  # pragma: allowlist secret
license: "YOUR_STREAM_LICENSE_KEY"
