name: Code Review GPT

# on:
#     pull_request:
#       branches: [master]
  
# on: [pull_request]
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Code Review GPT
      uses: mattzcarey/code-review-gpt@v0.1.5
      with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: 'gpt-3.5-turbo'
          GITHUB_TOKEN: ${{ github.token }}