name: Code Review GPT

# on:
#     pull_request:
#       branches: [master]
  
on: 
  pull_request:
    types: [opened, reopened, review_requested, ready_for_review]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Code Review GPT
      shell: bash
      run: npx code-review-gpt review --ci=github --model=$MODEL --debug
      
      env:
        MODEL: ${{ inputs.MODEL }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        # GITHUB_SHA: ${{ github.sha }}

          